[project]
name = "introduction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.35.77",
    "dependency-injector>=4.44.0",
    "mypy-boto3-s3>=1.35.76",
    "pydantic>=2.10.3",
]
